# -*- org-src-preserve-indentation: t; -*-
#+PROPERTY: header-args :exports none

bmo-systems repo is responsible for:

1. generating tarballs of the perl dependencies ("vendor bundles")
2. uploading the above to an amazon s3 bucket
3. generating several related docker images

* How-To
** Add perl dependencies to BMO

   Adding dependencies to BMO (or bugzilla in general) involves adding them to Makefile.PL.
   Getting these dependencies deployed to our infrastructure is more complicated.

   You will need (at least) a centos 6 install, and an ubuntu 14.04 install. On
   each, you will want to checkout the BMO code and an unpacked copy of the
   vendor tarball for that platform.

   #+BEGIN_SRC sh :exports code
   perl Makefile.PL
   make cpanfile GEN_CPANFILE_ARGS="-D bmo"
   carton install
   #+END_SRC

After this, file cpanfile and cpanfile.snapshot should be added to bundle/PLATFORM/ and those changes commited.

** Upgrade perl dependencies
   This is the same as adding a dependency, except instead of "carton install" you run "carton upgrade".

* Configuration

#+BEGIN_SRC yaml :tangle ".circleci/config.yml" :noweb yes
# if this file ends in .yml, you should not edit it and edit circle.org instead.
version: 2

jobs:
  <<upload>>
  <<centos6>>
  <<ubuntu14>>
  <<bmo-base>>
  <<bmo-ci>>
  <<bmo-slim>>
  <<docker-centos6>>
  <<docker-ubuntu14>>

workflows:
  version: 2
  builders:
    jobs:
      - docker-centos6:
          <<only master>>
      - docker-ubuntu14:
          <<only master>>
  bundles:
    jobs:
      - centos6:
          <<only master>>
      - ubuntu14:
          <<only master>>
      - bmo-slim:
          <<only master>>
          requires:
            - centos6
      - bmo-base:
          <<only master>>
          requires:
            - centos6
      - bmo-ci:
          <<only master>>
          requires:
            - bmo-base
      - upload:
          <<only master>>
          requires:
            - centos6
            - ubuntu14
#+END_SRC

#+NAME: only master
#+BEGIN_SRC yaml
filters:
  branches:
    only: master
#+END_SRC

* docker jobs
jobs that build docker containers (bmo-base, bmo-ci, etc)

** bmo-base

#+NAME: bmo-base
#+BEGIN_SRC yaml
bmo-base:
  working_directory: /build
  docker:
    - image: docker:17.06.1-ce
      environment:
        DOCKERHUB_REPO: mozillabteam/bmo-base
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
  steps:
    - setup_remote_docker
    - checkout
    - attach_workspace:
        at: /build/upload
    - run:
        no_output_timeout: 20m
        working_directory: /build/docker/bmo-base
        command: |
          tar -zxf /build/upload/bmo/vendor.tar.gz bmo/vendor/ bmo/cpanfile bmo/cpanfile.snapshot
          docker-build
#+END_SRC

** bmo-ci

#+NAME: bmo-ci
#+BEGIN_SRC yaml
bmo-ci:
  working_directory: /build
  docker:
    - image: docker:17.06.1-ce
      environment:
        DOCKERHUB_REPO: mozillabteam/bmo-ci
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
  steps:
    - setup_remote_docker
    - checkout
    - run:
        working_directory: /build/docker/bmo-ci
        command: |
          docker-build
    - run:
        command: docker run -ti $DOCKERHUB_REPO env GITHUB_BASE_BRANCH=production TEST_SUITE=sanity runtests.sh
#+END_SRC

** bmo-slim

#+NAME: bmo-slim
#+BEGIN_SRC yaml
bmo-slim:
  working_directory: /build
  docker:
    - image: docker:17.06.1-ce
      environment:
        DOCKERHUB_REPO: mozillabteam/bmo-slim
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
  steps:
    - setup_remote_docker
    - checkout
    - attach_workspace:
        at: /build/upload
    - run:
        working_directory: /build/docker/bmo-slim
        command: |
          tar -zxf /build/upload/bmo/vendor.tar.gz \
            bmo/vendor/bin \
            bmo/local \
            bmo/cpanfile \
            bmo/cpanfile.snapshot \
            bmo/LIBS.txt \
            bmo/PACKAGES.txt
          docker-build

#+END_SRC


** docker-centos6
#+NAME: docker-centos6
#+BEGIN_SRC yaml
docker-centos6:
  working_directory: /build
  docker:
    - image: docker:17.06.1-ce
      environment:
        DOCKERHUB_REPO: mozillabteam/centos6
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
  steps:
    - setup_remote_docker
    - checkout
    - run:
        name: build docker container
        command: |
          docker-build -f bundle/centos6/Dockerfile
#+END_SRC

** docker-ubuntu14
#+NAME: docker-ubuntu14
#+BEGIN_SRC yaml
docker-ubuntu14:
  working_directory: /build
  docker:
    - image: docker:17.06.1-ce
      environment:
        DOCKERHUB_REPO: mozillabteam/ubuntu14
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
  steps:
    - setup_remote_docker
    - checkout
    - run:
        name: build docker container
        command: |
          docker-build -f bundle/ubuntu14/Dockerfile

#+END_SRC

* bundle jobs

All the jobs below are used to build collections of the perl dependencies that BMO needs.

** centos 6 job

This job creates the 'bmo' bundle, which is for use on centos 6 or RHEL 6 machines.
This is what production, vagrant, CI, and so on use.

#+NAME: centos6
#+BEGIN_SRC yaml :noweb yes
centos6:
  working_directory: /build
  docker:
    - image: centos:6.9
      environment: 
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
        NAME: bmo # named this for historical reasons
  steps:
    - checkout
    - run:
        name: install rpms
        command: /build/bundle/centos6/install-rpms
    <<build_bundles>>
#+END_SRC
** ubuntu 14.04 job

This job creates the 'mozreview' bundle, which is used by the version-control-tools bmoweb container.
It is used for mozreview and probably some other systems and is a huge burden that makes me sad.

#+NAME: ubuntu14
#+BEGIN_SRC yaml :noweb yes
ubuntu14:
  working_directory: /build
  docker:
    - image: ubuntu:14.04
      environment:
        PATH: /build/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
        NAME: mozreview # named this for historical reasons
  steps:
    - checkout
    - run:
        command: cp /build/bundle/ubuntu14/mysql.list /etc/apt/sources.list.d/mysql.list
    - run:
        name: install dependencies
        command: /build/bundle/ubuntu14/install-debs
    <<build_bundles>>
#+END_SRC

** upload job

This job just collects vendor.tar.gzs from other jobs and uploads them to an amazon S3 bucket.

#+NAME: upload
#+BEGIN_SRC yaml
upload:
  working_directory: /build
  docker:
    - image: alpine:latest
      environment:
        S3_BUCKET: moz-devservices-bmocartons
  steps:
    - run:
        command: |
          apk update
          apk add curl # installs ca certs
    - attach_workspace:
        at: /build/upload
    - run:
        name: install awscli
        command: |
          apk update
          apk add py-pip
          pip install awscli
    - run:
        working_directory: /build/upload
        command: |
          for file in */vendor.tar.gz; do
            aws s3 cp $file s3://$S3_BUCKET/$file;
          done
#+END_SRC

* Other pieces of code

Some bits of configuration used in multiple locations

** build_bundles steps

The following list of steps are used on all jobs that build vendor tarballs.

#+NAME: build_bundles
#+BEGIN_SRC yaml
- run:
    name: copy cpanfile and cpanfile.snapshot
    command: cp bundle/$CIRCLE_JOB/cpanfile* .
- run: build-prepare
- run: build-stage1
- run: build-stage2
- run: build-vendor-bundle $NAME
- persist_to_workspace:
    root: /build/upload
    paths:
      - "*/vendor.tar.gz"
- store_artifacts:
    path: '/root/.cpanm/work/*/build.log'
#+END_SRC

