#!/bin/bash
success=no
(( i = 1 ))
while (( ++i < 5 )); do
  apt-key adv --keyserver ha.pool.sks-keyservers.net \
      --recv-keys A4A9406876FCBD3C456770C88C718D3B5072E1F5 || continue
  apt-get update || continue
  apt-get --no-install-recommends -y install \
      apache2 build-essential cvs g++ git graphviz libapache2-mod-perl2 \
      libgd-dev libgmp3-dev libmysqlclient-dev libssl-dev curl \
      mysql-client mysql-server patchutils pkg-config unzip wget || continue
  success=yes
  break
done
[[ $success == yes ]] || exit 1